using System.Collections.Generic;
using ICSharpCode.NRefactory.PatternMatching;
using System.Linq;
using ICSharpCode.NRefactory;

namespace Expresso.Ast
{
	/// <summary>
	/// シーケンス(リストや連想配列など)のリテラル式。
	/// Represents the literal form of a sequence initialization.
	/// </summary>
    public class SequenceInitializer : Expression
	{
        /*public override ICSharpCode.NRefactory.TextLocation StartLocation{
            get{
                var first_item = Items.FirstOrDefault();
                return (first_item != null) ? first_item.StartLocation : base.StartLocation;
            }
        }

        public override ICSharpCode.NRefactory.TextLocation EndLocation{
            get{
                var last_item = Items.LastOrDefault();
                return (last_item != null) ? last_item.EndLocation : base.EndLocation;
            }
        }*/

		/// <summary>
        /// シーケンス生成に使用する式群。
		/// Expressions generating each element of a sequence object.
        /// </summary>
        public AstNodeCollection<Expression> Items{
            get{return GetChildrenByRole(Roles.Expression);}
		}
		
		/// <summary>
		/// この式群を評価した結果生成されるオブジェクトのタイプ。
		/// The type of sequence object generated by this node.
        /// Note that it doesn't contain any information about the element type until after
        /// the type check phase.
		/// </summary>
        public SimpleType ObjectType{
            get{return GetChildByRole(Roles.GenericType);}
            set{SetChildByRole(Roles.GenericType, value);}
		}

        public SequenceInitializer(SimpleType objType, IEnumerable<Expression> seqItems, TextLocation start, TextLocation end)
            : base(start, end)
		{
            ObjectType = objType;
            if(seqItems != null)
                Items.AddRange(seqItems);
		}

        public override void AcceptWalker(IAstWalker walker)
		{
            walker.VisitSequenceInitializer(this);
		}

        public override TResult AcceptWalker<TResult>(IAstWalker<TResult> walker)
        {
            return walker.VisitSequenceInitializer(this);
        }

        public override TResult AcceptWalker<TResult, TData>(IAstWalker<TData, TResult> walker, TData data)
        {
            return walker.VisitSequenceInitializer(this, data);
        }

        #region implemented abstract members of AstNode

        protected internal override bool DoMatch(AstNode other, Match match)
        {
            var o = other as SequenceInitializer;
            return o != null && ObjectType.DoMatch(o.ObjectType, match) && Items.DoMatch(o.Items, match);
        }

        #endregion
	}
}

